CC=g++

all: HH_Condition NMR_frequency 

HH_Condition: HH_Condition.cpp
	$(CC) HH_Condition.cpp -o HH_Condition

NMR_frequency: NMR_frequency.cpp
	$(CC) NMR_frequency.cpp -o NMR_frequency


clean:
	rm -rf H_Condition NMR_frequency
